{"timestamp":"2025-05-23T18:10:36.317Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"error message","data":{"message":"test error"}}
{"timestamp":"2025-05-23T18:10:36.533Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"error with cause","data":{"message":"Test error"}}
{"timestamp":"2025-05-23T18:10:36.744Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"error with data","data":{"message":"[object Object]"}}
{"timestamp":"2025-05-23T18:10:36.956Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"Custom error log","data":{"message":"Custom error occurred"}}
{"timestamp":"2025-05-23T18:10:36.958Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"Error cause","data":{"cause":"Error: Inner error\n    at <anonymous> (/Users/paul/Projects/EffectiveAgent/src/services/core/logging/__tests__/service.test.ts:297:24)\nError: Parallel error\n    at <anonymous> (/Users/paul/Projects/EffectiveAgent/src/services/core/logging/__tests__/service.test.ts:299:26)\nError: Final error\n    at <anonymous> (/Users/paul/Projects/EffectiveAgent/src/services/core/logging/__tests__/service.test.ts:300:26)"}}
{"timestamp":"2025-05-23T18:10:36.958Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"Error occurred","data":{"message":"[object Object]"}}
{"timestamp":"2025-05-23T18:19:36.935Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"error message","data":{"message":"test error"}}
{"timestamp":"2025-05-23T18:19:37.154Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"error with cause","data":{"message":"Test error"}}
{"timestamp":"2025-05-23T18:19:37.364Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"error with data","data":{"message":"[object Object]"}}
{"timestamp":"2025-05-23T18:19:37.576Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"Custom error log","data":{"message":"Custom error occurred"}}
{"timestamp":"2025-05-23T18:19:37.578Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"Error cause","data":{"cause":"Error: Inner error\n    at <anonymous> (/Users/paul/Projects/EffectiveAgent/src/services/core/logging/__tests__/service.test.ts:297:24)\nError: Parallel error\n    at <anonymous> (/Users/paul/Projects/EffectiveAgent/src/services/core/logging/__tests__/service.test.ts:299:26)\nError: Final error\n    at <anonymous> (/Users/paul/Projects/EffectiveAgent/src/services/core/logging/__tests__/service.test.ts:300:26)"}}
{"timestamp":"2025-05-23T18:19:37.580Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"Error occurred","data":{"message":"[object Object]"}}
{"timestamp":"2025-05-23T18:21:40.236Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"error message","data":{"message":"test error"}}
{"timestamp":"2025-05-23T18:21:40.477Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"error with cause","data":{"message":"Test error"}}
{"timestamp":"2025-05-23T18:21:40.687Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"error with data","data":{"message":"[object Object]"}}
{"timestamp":"2025-05-23T18:21:40.897Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"Custom error log","data":{"message":"Custom error occurred"}}
{"timestamp":"2025-05-23T18:21:40.899Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"Error cause","data":{"cause":"Error: Inner error\n    at <anonymous> (/Users/paul/Projects/EffectiveAgent/src/services/core/logging/__tests__/service.test.ts:321:24)\nError: Parallel error\n    at <anonymous> (/Users/paul/Projects/EffectiveAgent/src/services/core/logging/__tests__/service.test.ts:323:26)\nError: Final error\n    at <anonymous> (/Users/paul/Projects/EffectiveAgent/src/services/core/logging/__tests__/service.test.ts:324:26)"}}
{"timestamp":"2025-05-23T18:21:40.900Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"Error occurred","data":{"message":"[object Object]"}}
{"timestamp":"2025-05-23T18:26:12.690Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"error message","data":{"message":"test error"}}
{"timestamp":"2025-05-23T18:26:13.718Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"error with cause","data":{"message":"Test error"}}
{"timestamp":"2025-05-23T18:26:14.741Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"error with data","data":{"message":"[object Object]"}}
{"timestamp":"2025-05-23T18:26:15.769Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"Custom error log","data":{"message":"Custom error occurred"}}
{"timestamp":"2025-05-23T18:26:15.773Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"Error cause","data":{"cause":"Error: Inner error\n    at <anonymous> (/Users/paul/Projects/EffectiveAgent/src/services/core/logging/__tests__/service.test.ts:321:24)\nError: Parallel error\n    at <anonymous> (/Users/paul/Projects/EffectiveAgent/src/services/core/logging/__tests__/service.test.ts:323:26)\nError: Final error\n    at <anonymous> (/Users/paul/Projects/EffectiveAgent/src/services/core/logging/__tests__/service.test.ts:324:26)"}}
{"timestamp":"2025-05-23T18:26:15.775Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"Error occurred","data":{"message":"[object Object]"}}
{"timestamp":"2025-05-23T18:26:55.204Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"error message","data":{"message":"test error"}}
{"timestamp":"2025-05-23T18:26:56.229Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"error with cause","data":{"message":"Test error"}}
{"timestamp":"2025-05-23T18:26:57.249Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"error with data","data":{"message":"[object Object]"}}
{"timestamp":"2025-05-23T18:26:58.267Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"Custom error log","data":{"message":"Custom error occurred"}}
{"timestamp":"2025-05-23T18:26:58.272Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"Error cause","data":{"cause":"Error: Inner error\n    at <anonymous> (/Users/paul/Projects/EffectiveAgent/src/services/core/logging/__tests__/service.test.ts:321:24)\nError: Parallel error\n    at <anonymous> (/Users/paul/Projects/EffectiveAgent/src/services/core/logging/__tests__/service.test.ts:323:26)\nError: Final error\n    at <anonymous> (/Users/paul/Projects/EffectiveAgent/src/services/core/logging/__tests__/service.test.ts:324:26)"}}
{"timestamp":"2025-05-23T18:26:58.274Z","level":{"_tag":"Error","syslog":3,"label":"ERROR","ordinal":40000},"message":"Error occurred","data":{"message":"[object Object]"}}
